# Generated by Django 6.0.6 on 2026-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='GST Number'),
        ),
    ]
