# Generated by Django 6.0.6 on 2026-07-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sitesettings_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registered_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
