# Generated by Django 6.0.6 on 2026-07-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sitesettings_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='registered_address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='support_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='support_phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('submitted', 'Payment Submitted'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
