# Generated by Django 6.0.6 on 2026-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_sitesettings_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policypage',
            name='footer_order',
            field=models.PositiveIntegerField(default=0, help_text="Lower numbers appear first in the 'Our Policy' footer column."),
        ),
        migrations.AddField(
            model_name='policypage',
            name='show_in_policy_footer',
            field=models.BooleanField(default=False, help_text="Show this page as a link under the footer's 'Our Policy' column. Leave off for pages already linked elsewhere (About Us, Contact, Shipping & Returns, etc.)."),
        ),
    ]
